#!/usr/bin/env python3

import sys
sys.path.insert(0, './python3/')
from napi import *

N4S = Napi()

def getSpeed():
    speed = 0
    return speed
def getAlpha(speed):
    alpha = 0

    return alpha

def my_custom_update():
    speed   =   getSpeed()
    alpha   =   getAlpha(speed)
    middle  =   N4S.getRayAt(15)

    N4S.setThrust( speed, refresh = True )
    N4S.setDirection( alpha, refresh = True )

if __name__ == '__main__':
    N4S.start(my_custom_update)
